# Generated by Django 4.2.16 on 2024-10-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eventtype',
            field=models.IntegerField(choices=[(0, 'MudRun'), (1, 'Hiking'), (2, 'Other')], default=0),
        ),
    ]
